language: node_js
node_js:
    - "6.4.0"
script: npm test
before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install
after_success:
    "curl --ftp-create-dirs -T karma.conf.js -u $uuu:$ppp ftp://ngangular2.com/httpdocs/"