language: node_js
node_js:
- 6.4.0
script: npm test
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install
env:
  global:
    secure: OsqIX4gSNoBuR6bbcqgZbYKUCav00+xMIVMNcGUyeOYxtYci16PLHqPSFQb+35rNHSSNGnpEbn56cz3u2ntTUUXNThG6s5tP5ANdoPIDNfbbYzwAZXu2/2bh3L1Ct6aA2sExsVGyeTQ1XAHst0Ee1Pj6l3w0+CWbF9Wj2hFJWavENalzG8W5+y0WjPtSCqUUw734Q5O97LFDH4p9wPXFC9wbB/aP1GQDOGKjQA8I5dISo8oDriXdIF97XpLPgTA4SuaxPduUQ6dmCEZBB/cjX9S7telj7LnCw3QdiKC83nysCBOCEp4qBInGqXH8WGwpDyYjBIsAMQkvNAMD+7ly2W3jUidrI/XD6H8B8Jj6MJh5yFGZuOGuT5lWVcS0chAMPDXJZ7usa961HyPDnXSihaLesQFI6jelsSthmo9ZetEzwNM1P3cgBSGufTfvymhWaq3NO1HsVtYLbeJsuk+kJ2dL5nwGwmiRywHaYemm99fZeRvsYQvAKYAohSpBBPjDdhGRKv/WaotrVzt3ofqos7zfGrA6obYxr3Km3kHbHRcFD7flgjC9IBzAoueHNWwot+fONqK42BC4aZDdL07JdxFYTp6+W975GZFGnVuCuPZUygnLEUJmUDcUK7kSU3CrboPP8USZqFVwFUh4jY+ywuDfIwtMpzeMdOPzY75dTJU=
after_success: 
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
    
