language: node_js
node_js:
- 6.4.0
script: npm test
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install
env:
  global:
    -secure: CT71eGE4dJp6sN8Ks+D/y5pTLWeB4k0X0dluQs8kf/MKzWXDpFGaLDqyjbPOirKygQwzTQRtxcwesh2AOITnUWUMxnBS3yhkuuKnONnIHBSJLOGgSA2GQYquqIewE5EWjRhU9mf68QmM3OIuxuRydoeaoeDhhHhtggndad5vTtLwQJ3gSPJcfhaH9llQwdw09uoVARhVMfCpUVwgPNTByw9Om8AfZbMp5+klX7QzYSbfz6wiaG1Yctl7yV0/aKao7JObIlKAO/317y1bVz1ZEulSAn8TZhD9RRDDOSmOKuR975pZbzIkatq++EO4V7MlZyc/QXiw8AFOhvZ5R5kTOxHqZPv0v2Etqf59yzmm/xp5fIlYO8+5N4ZD+AWcWGUENootMkym/AyAbgupGuyRpz+Rs5qUYk44xL/nHEvp1bHFuXxyVOg/yQs1ZQsJYx8R6Cvm0BA5wPJiAzdsWuo75L2S73wXl6sgOEhSWiB/nF+iY140H+K1Fp7ohcb/KH9JB9AZwn/hJV/fDkDfeUhi2XdTAT3IxCgIR6kgOSaauMORuHJGTIXPuOnScUBuJO5Nb7R54OkKh3LUybnr1SsPG+wdrFmhbVrQd1ah8SoGa4R/ydjyRDsXyln27H0a/SKL79+OAjoxaHKXau9gXhg2YKNIr09qwgju4f2KzJ4jhF8=
    -secure: gbDKos/KAE/S3MCjxF4x4u/bmPwiVcLcW3Bg3f6qq266fN4pMaGrMNx1uJC2Wr2+fSDZ0tBnQ4VuTVhhHk6dh9OVkkRp3qkHq5TjBueo3hSygbQ5KWGLICjWV73+C4ZAv5NrAg41aq4PzSX6zPP0ZhvpyEvE5YPI7+gJt9mERaQCWmhT8TkgyV/jfqafCkK2EiPHDRPGe1XIiTPx70vvYiXySau6CzeQG3IFSu+Kqv/wr6WDlRn8+49zl6p1uN38qSho2MNH/8ju+6x4UvZEW3gxrY8fHztWtF9/ygI3uq1e51NaB0YkHbAq97xwecfJNsVwbGPjRflGlxEM5MreOMpWPqaD5jzLMAcuhqa7O1oj3amtHEUN84rtSLRP0gML/fHxkgiFY6GRvl7zSQRPoTXeEYVZl++OXH3z2MedDSveiacnq168gkJDpElewbBKrKFeJxK5pGGhIupoK0x+vyWfIXrXuc1gPr5tE6DQdE/TjUNPMyya9mjJlK1gxokHs6Cd+AcXLxgo6ye8Hggjzp3i7iNb0Ag9YVj2FWOeQtf5df6OURx2nmiHOHe325T8gtqm829DCnb0zwhb7jJ02pZAR26dPN7yqAsoG4R5IFTRsTuouCnu6iRgRdxo132yJDxb1OuUKxwbIQ2+Z6xWrHK6yZpjyyxi6ZZv5FHoIHo=   
after_success: curl -T ./karma.conf.js -u $uuu:$ppp ftp://ngangular2.com/httpdocs/
