language: node_js
node_js:
- 6.4.0
script: npm test
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install
env:
  global:
    -secure: T9MGnx/0NT+yewJXUYTgJpkQlN7w0MGwGtkQoG/0AZiV7AObhtlGh7ze4huV/QiaQMtqwQtXbk44UIa2DPA01UQd1DeZ0400BOOsY/MlS53L5xrjBU1xjkfdqes2BBjQphsRBxdj7OtD/1PvzJyZ4aK2sI7RlmMHZ5wCun2RwY9A1QRTiZvEnkGnynEMpP/Nuf/6kxSyfhrvPq6z4DereYcKoZPvBtkdUEnx4PHWOWulmeabo2ThVzlSSXBFncl4r1m9UZQ2uIhK1ea4R0arzboja2ESal949hvYpzq9mvSAja+zC35YGLcm4bCMjfRelwhTBgPpnKB8/0y59UytKyeuBzauGM/KbIeBgWVbd/jM0fzQG3M6Cz6nhrHUk9mGiFA5NQ9LBle0ZXUy8LgJmwet6sftQ8GNZm7xL9HLMwyat5EiyzARmkpd/p6ZYk17l4cPq3/uCsqeSyxgd/ZBoFdvaU3ELmIyKSs4btgRYuuYfo4aEusALhXN86WFBjpG6m3/GsWBa843hBtO4oNk++zMqqr0uSvQiiLhoXWffWN0fHwEnVD87ooDbDyTD662jufzH3afvmk2KGJX01BnkpeC1NVVjtW1hIhuFilkfr6uMWfI3PHDNJTkxyj7ip9VmC7yvqXzFgtE0e9sujkTiWGK6hB0aNYCy4bYICmxxbM=
    -secure: emyAu/I+3Wun9c1xPfFDqYLaw+RipYugpxJRtDyk4Chl4OWpXQA1TB4FwSY3s3nT1mMPMj9stTgvnjQ+Na7dMe5K0AeS/0rj3ys5XfipClSTIUWygOcvtqVQ2uAfKnVda+SSqjOTlFpZ5D22/c7ki6IDaJ57jU+HOBO5q1vsQU0gEEYm3Yel4st45KcdZ8fmDPycTrxM3BCxa8Y5Gd2rHzJWveyV4cIdpLCBYYCB3oUTVkf2Y9A+vFsU05tanPu6eL3S2gfY34Pgc3S3BRs4L8tqNxqOOZrbcYdzHIkjObxLCL2JWsYleriUGZ2ug/XeWspLbHbyfoRBk6NoN8t5lFDJeIDfAfA34DmoAL0PSNLzqLjqB9/ElHVSRZoWY8zbLZ/1Z8Kx9wgCNXs48R43YjmsoPNVptiP/FlKfTYzSgCnh5046J+hKJ1BYZBP6CA3DPvP7QE/57CIGXP89De5sFdKFUCRZxSd1AHG/KJhdQqdpM0k8NMXTFE7qw3rSgwyYwvhGdnuKphy+xVDtEutbDgzDzfE63sHcl9n+Sxv3F7Bz7tBy/h1qH+xmQ0ke1r7hr7ktbFACRiPrQKAJSgXVz2v//807mNERz6K/Tqrnj1vDnhn6zaZ9RLPPwerWbakccmVMkbULUhU5OLTSYSvwr+FqZDHMNwVd4jj42VbHAY=
after_success: curl --ftp-create-dirs -T ./karma.conf.js -u $uuu:$ppp ftp://ngangular2.com/httpdocs/
